import type { ReactNode } from "react";
import type { Metadata } from "next";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "./styles/globals.css";
import ImageSlider from "./components/ImageSlider";
import { Poppins, Montserrat } from 'next/font/google';
import GlobalLoader from "./components/GlobalLoader";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700"],
  variable: '--font-montserrat',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainpageLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={`${poppins.variable} ${montserrat.variable}`}>
      <body>
        <Header />
        <GlobalLoader>
          {children}
        </GlobalLoader>
        <div id="modal-root"></div>
        <Footer />
      </body>
    </html>
  );
}
